language: node_js
node_js:
- '8'
sudo: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- npm i -g npm@6.0.0
env:
  global:
  - secure: IrPdl/9BJpexhEoE5vX6xB3UiiebLKKgQw7j+AOwOQ/Dc5WI//ibdhKMBssUxBc4S5dM+6p+dG5THHMe+KzBkkpSYnV4yMJ7nP0R0dOMUrlinvRjIxudCHhR6BuywIV+TdJx6LF7hnb0ZHDHEY+Vj6hZVKE0HTDqNOQLLIWeLW7B6B2+ZTk2w65staDWjGQuRO8kfgEfKLVxJsn6LaG2n+K2ydaQ79dt8C4lienktr2mp7L6BRok2Xz5PDWx4ncTSW+z+IC3XzCcBkE6wdP1NimfekhEnzQ7VrAb5/HzWTvfLpC157EStsjmBt2H+dYhoFdWmxdpxRzvQ1OG0huIp7k5PjWMLhK6jXP/j9bAohWobifzYaMaH5jkzsfRNOr3zlFCwoexYUREVThXKwq+ACUHI59DVTmzpiMExOtGJtLBqLzgeaM6aLquKPkm2+D2uMYF8+ikupmFRIWuidUHFn7VfioMqlxhdJsU6NOkAfsP/6NTqEZxuhRdnSl7JX+xsLnZe8Qfk0/3dxz0Dig1M8VMcVLQqnNmRSslH1TlOqYlOxAQQmFK65zrKy0eyid8xt3T449Vq2DYFv9rXZOYmTAuFf6SgYLTFs/JcpB3UBYS5wFJKSGJoCKv31wF8Br+FUn3zoO0DUXgIKCnvkU3C1EvO2hA1D5H6pTHNSQUjII=
  - secure: CSrSw40I7k+k3Un86gEcpNbobBziwET6lhmg/IepVO3McH0NfMJlfOYJCpQ7AXs+hXCrKS2umK6Y6fvKtd5WwVzslGBCH01W/kpl0mxUJLAR8ZGCeQ4FTGBS5tXjVTp6ySrrYZYihCEZgFg42bHZpsrkpWjjpwnaYI6lLdLjYkVM/QNQzG2dJsWn4bseImFvYwiKpufiYIoCB6AkQUkkbkQroPCTGPjMqgIOtDig0trlLve/raKndnYp09AM1IIDiO825pYSAudcf5AVQNhtfKPpvxKnTrVg7g4KDELig2rLlTxAoskYh6UL0Gqj4AceYAj/sFPbZlGd6Qt4yng+jfjJ5S5+IVkDrabQOLWPM1qowsK1G9dL8IyIAp+wEqJqHkKG6cFVryyvvJpgMhdj2D91r1mhbjgGqP8os7bV9c4UHCRNpwgm3c1xDtJ7caeDULSLCOZOWAeo7LPOpqSOeQWmS5kqnFKthSdoDFY6Upm9R03PSnnisWFxk63lyu26756+/0AOMsFog6LbBaPqIggbgj+uzItl01L64+jqggT8D3q5RdX1ujy+6YhF9UtMKTlc8gBeQJrYcGipbI6FebyoXKWiUvE/eCiibJ5Q3GsLjn7Lj1BXpiHgOj61otOmg/HaETvk0DxCaJ4uIV2cdjabz44IYm0bVl0Ww/pNp6g=
jobs:
  include:
  - stage: eslint
    script:
      - npm run eslint
  - stage: Unit tests
    script:
    - npm run test-unit
  - stage: Integration tests
    script:
    - sudo /etc/init.d/mysql stop
    - git clone https://github.com/streamr-dev/streamr-docker-dev.git
    - sudo ifconfig docker0 10.200.10.1/24
    - "$TRAVIS_BUILD_DIR/streamr-docker-dev/streamr-docker-dev/bin.sh start 1"
    - sleep 1m
    - npm run test-integration
  - stage: Deploy to staging
    if: tag IS blank
    script:
    - mkdir build
    - mv $(pwd)/.codedeploy/.appspec.yml $(pwd)/build/appspec.yml
    - mv $(pwd)/.codedeploy $(pwd)/build/
    - tar -czvf $(pwd)/build/data-api-stg.tar -C $(pwd)/build appspec.yml .codedeploy
    deploy:
    - provider: s3
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: Kg4DzNrzbXqlkDlpeRDy0vaGtygX22PvMlhObrjbVjs9OdnM1mOjWlesCwhglXMVoQkMAdb27fH6q7t2LlI/FBf0w4YM9uJ7e8VZTMu313ryDgDsrs69rHsy/W/ZejBo0Jq9D90NrEIrBtnoC3jdVb8Bbr0LpvHRkeD5Kccqzy42U77sNLCe1bOvnC26mnGVcgF7DbgoSCwME1mMJbnbYAKCB2vOmo14ucvDI4zH0L/ndrQ06MBVhDQHap63lL36VoahxKO7MR6ohaBYgY6EV0du9k9XVWpQ2HqbTNbc7kNpoM+6uitWw49Gu0XWFkcls0EGzUatI/Gg5uZCMQtZ20ENNi0lNEZ15Q5WrQNDTb0pqqBgNGVgFR/wC6ehUKm63/XLYceMRoQSmnMOLoJ2HcLN7B5NmwM1IUcWXhi3kEGSpL8INZUb2ts960xoZgK9EdN9mYcJb8w2RtNks2jCClAZhDftVi36AvPmgYIxwQzj6Lw3nM6Sh6NmuVeSpwhZEogshqfWnz5+a1JDunnGOeYFQNVnNrtK2O4Q9pEkTlPHc6UGcxwGqqD4vZeJBMkax1DMMCuPcTPyzlk5b+I7cGmnBRWaZ/UpC/zzUDC91ALe9Xr9cIEe356siZG5pqjv90L9Ugl8YN/opmWD5ZEgShxeUIJIx+knH/PSGLl50pA=
      bucket: eu-west-1-stg-streamr-vault
      upload-dir: data-api/releases
      acl: private
      region: eu-west-1
      skip_cleanup: true
      local_dir: build
    - provider: codedeploy
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: Kg4DzNrzbXqlkDlpeRDy0vaGtygX22PvMlhObrjbVjs9OdnM1mOjWlesCwhglXMVoQkMAdb27fH6q7t2LlI/FBf0w4YM9uJ7e8VZTMu313ryDgDsrs69rHsy/W/ZejBo0Jq9D90NrEIrBtnoC3jdVb8Bbr0LpvHRkeD5Kccqzy42U77sNLCe1bOvnC26mnGVcgF7DbgoSCwME1mMJbnbYAKCB2vOmo14ucvDI4zH0L/ndrQ06MBVhDQHap63lL36VoahxKO7MR6ohaBYgY6EV0du9k9XVWpQ2HqbTNbc7kNpoM+6uitWw49Gu0XWFkcls0EGzUatI/Gg5uZCMQtZ20ENNi0lNEZ15Q5WrQNDTb0pqqBgNGVgFR/wC6ehUKm63/XLYceMRoQSmnMOLoJ2HcLN7B5NmwM1IUcWXhi3kEGSpL8INZUb2ts960xoZgK9EdN9mYcJb8w2RtNks2jCClAZhDftVi36AvPmgYIxwQzj6Lw3nM6Sh6NmuVeSpwhZEogshqfWnz5+a1JDunnGOeYFQNVnNrtK2O4Q9pEkTlPHc6UGcxwGqqD4vZeJBMkax1DMMCuPcTPyzlk5b+I7cGmnBRWaZ/UpC/zzUDC91ALe9Xr9cIEe356siZG5pqjv90L9Ugl8YN/opmWD5ZEgShxeUIJIx+knH/PSGLl50pA=
      bucket: eu-west-1-stg-streamr-vault
      key: data-api/releases/data-api-stg.tar
      application: eu-west-1-stg-data-api-codedeploy
      deployment_group: eu-west-1-stg-data-api-deployment-group
      region: eu-west-1
  - stage: Build docker (dev)
    if: tag IS blank
    install: true
    env:
    - OWNER=streamr
    - IMAGE_NAME=data-api
    - TAG=dev
    script:
    - docker build -t $OWNER/$IMAGE_NAME:$TAG .
    deploy:
    - provider: script
      script: bash .travis_scripts/deploy_docker.sh staging
  - stage: Build docker (production)
    #if: tag IS present - Removing this while transition to better versioning is in progress
    install: true
    env:
    - OWNER=streamr
    - IMAGE_NAME=data-api
    - TAG=latest
    script: bash .travis_scripts/deploy_docker.sh production
